name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GKE_CLUSTER: 'icb-web-deploy'
  GKE_ZONE: 'southamerica-east1'
  DEPLOYMENT_NAME: 'icb-web-deployment'
  REPOSITORY: 'icb_web'
  IMAGE: 'icb_web:latest'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/772107785669/locations/global/workloadIdentityPools/icb-web-pool/providers/my-provider'
  REACT_APP_YOUTUBE_API_KEY: ${{ secrets.REACT_APP_YOUTUBE_API_KEY }}
  REACT_APP_YOUTUBE_CHANNEL_ID: ${{ secrets.REACT_APP_YOUTUBE_CHANNEL_ID }}

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Build Docker container'
        run: |-
          DOCKER_TAG="gcr.io/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}"

          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${{ github.sha }}" \
            --build-arg GITHUB_REF="${{ github.ref }}" \
            .

      - name: 'Push Docker container to Google Container Registry'
        run: |-
          gcloud auth configure-docker
          docker push "${DOCKER_TAG}"

      - name: 'Set up Kustomize'
        run: |-
          curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          chmod u+x ./kustomize

      - name: 'Deploy to GKE'
        run: |-
          ./kustomize edit set image ${{ env.REPOSITORY }}=${DOCKER_TAG}
          ./kustomize build k8s | kubectl apply -f -
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
          kubectl get services -o wide

      - name: 'Set logging options'
        run: |-
          gcloud builds submit --config=cloudbuild.yaml --substitutions=_IMAGE="${DOCKER_TAG}" --logging=CLOUD_LOGGING_ONLY