name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GKE_CLUSTER: 'icb-web-deploy'
  GKE_ZONE: 'southamerica-east1'
  DEPLOYMENT_NAME: 'icb-web-deployment'
  REPOSITORY: 'icb_web'
  IMAGE: 'gcr.io/icb-web-434214/icb_web:latest'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/772107785669/locations/global/workloadIdentityPools/icb-web-pool/providers/my-provider'
  REACT_APP_YOUTUBE_API_KEY: ${{ secrets.REACT_APP_YOUTUBE_API_KEY }}
  REACT_APP_YOUTUBE_CHANNEL_ID: ${{ secrets.REACT_APP_YOUTUBE_CHANNEL_ID }}

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Configure Docker for Google Container Registry'
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth configure-docker

      - name: 'Grant serviceusage.serviceUsageViewer Role'
        run: |
          gcloud projects add-iam-policy-binding ${{ env.PROJECT_ID }} \
            --member="serviceAccount:772107785669@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
            --role="roles/serviceusage.serviceUsageViewer" \
            --condition="expression=request.time < timestamp('2024-10-03T15:46:34.348Z'),title=cloudbuild-connection-setup"

      - name: 'Build and Push Docker Image using Cloud Build'
        run: |
          gcloud builds submit --tag $IMAGE .

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Deploy to GKE'
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml